---
- name: install yum-utils
  yum:
    name: yum-utils
    state: installed

- name: add repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: enable docker service
  systemd:
    name: docker
    enabled: yes

- name: Configuring remote access with systemd unit file
  copy:
    src: files/startup_options.conf
    dest: /etc/systemd/system/docker.service.d/startup_options.conf

