---
- hosts: all
  remote_user: azureuser
  become: true
  gather_facts: no

  roles:
    - install-docker

- hosts: tag_role_manager
  remote_user: azureuser
  become: true
  gather_facts: no

  roles:
    - generate-certificates
    - docker-remote-access
