---
- name: Init Swarm Master
  hosts: tag_role_manager
  remote_user: azureuser
  become: True
  gather_facts: False
  tasks:
    - name: Get Swarm status
      shell: set -o pipefail && docker info | grep Swarm | cut -d ":" -f2
      register: swarm_status
      changed_when: false

    - name: Swarm Init
      command: docker swarm init --advertise-addr {{ hostvars[inventory_hostname].ansible_host }}
      when: not "active" in swarm_status.stdout

    - name: Get Worker Token
      command: docker swarm join-token worker -q
      register: worker_token
      changed_when: false

    - name: Show Worker Token
      debug: var=worker_token.stdout

- name: Join Swarm Cluster
  hosts: tag_role_worker
  remote_user: azureuser
  become: True
  gather_facts: False
  vars:
    token: "{{ hostvars[groups['tag_role_manager'][0]]['worker_token']['stdout'] }}"
    master: "{{ hostvars[groups['tag_role_manager'][0]]['public_ipv4_addresses'] | to_json }}"
  tasks:
    - name: Get Swarm status
      shell: set -o pipefail && docker info | grep Swarm | cut -d ":" -f2
      register: swarm_status
      changed_when: false

    - name: Join Swarm Cluster as a Worker
      command: docker swarm join --token {{ token }} {{ master }}:2377
      when: not "active" in swarm_status.stdout
      register: worker

    - name: Show Results
      debug: var=worker.stdout

    - name: Show Errors
      debug: var=worker.stder
