- name: Create Azure VMs
  hosts: localhost
  connection: local
  vars_files:
    - ../group_vars/keys.yml
    - ../group_vars/global.yml

  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: westeurope

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ virt_network }}"
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ virt_network }}"

  - name: Create public IP addresses for VMs
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ ip }}_{{ item }}"
    loop:
      - 1
      - 2
    register: pip_output

  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ network_security_group }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound

  - name: Create virtual network inteface cards for VMs
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ nic }}_{{ item }}"
      virtual_network: "{{ virt_network }}"
      subnet: "{{ subnet }}"
      public_ip_name: "{{ ip }}_{{ item }}"
      security_group: "{{ network_security_group }}"
    loop:
      - 1
      - 2

  - name: Create VMs
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}{{ item }}"
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ ssh_keys }}"
      vm_size: Standard_DS1_v2
      network_interfaces: "{{ nic }}_{{ item }}"
      os_disk_size_gb: 40
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
    loop:
      - 1
      - 2
    tags: VM

  - debug:
      msg: "Public IP Address 1: {{ pip_output.results[0].state.ip_address }}"

  - debug:
      msg: "Public IP Address 2: {{ pip_output.results[1].state.ip_address }}"

